_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('animal/', include('animal_classification.urls', namespace="animal")),
    path('admin/', admin.site.urls),
]
#
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

animal_classification/urls.py
from django.urls import path

# from animal_classification.views import IndexView, TestView, UploadView, ImageUpload, ImageDetail, ImageClassify
from animal_classification.views import upload_image, classify_image, ClassificationResultView

app_name = 'animal'

urlpatterns = [
    # path('', IndexView.as_view(), name="index"),
    # path('upload/', ImageUpload.as_view(), name='upload'),
    path('upload/', upload_image, name='upload'),
    path('classify/<pk>/', classify_image, name='classify'),
    path('result/<pk>/', ClassificationResultView.as_view(), name='result'),
    # path('detail/<pk>/', ImageDetail.as_view(), name='detail'),
    # path('result/', )
]

animal_classification/models.py
from django.db import models
from django.shortcuts import resolve_url


class Image(models.Model):
    content = models.FileField(upload_to='image/origin/%Y/%m/%d')
    comment = models.CharField(max_length=200, blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)  # 레코드 생성시 현재 시간으로 자동 생성

    def __str__(self):
        return self.content.url

    def get_absolute_url(self):
        url = resolve_url('animal:detail', self.pk)
        return url


class ClassificationResult(models.Model):
    origin = models.OneToOneField(Image, on_delete=models.CASCADE)
    label = models.CharField(default='?', max_length=200)
    probability = models.FloatField(default=0.0)

    def __str__(self):
        return "('{}', {:f}%)".format(self.label, (self.probability * 100))

    def get_absolute_url(self):
        url = resolve_url('animal:result', self.pk)
        return url

animal_classification/forms.py
from django import forms

from animal_classification.models import Image


class UploadImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['content', 'comment']

animal_classification/views.py
import os

from django.shortcuts import redirect, render
from django.views.generic import DetailView

from animal_classification.forms import UploadImageForm
from animal_classification.models import Image, ClassificationResult
from classification.AnimalClassification.classification import AnimalClassification


def upload_image(request):
    if request.method == 'POST':
        form = UploadImageForm(request.POST, request.FILES)
        if form.is_valid():
            print("valid")
            image = form.save()
            return redirect('animal:classify', pk=image.pk)
        else:
            print("not valid")
            form = UploadImageForm()
    else:
        form = UploadImageForm()
    return render(request, 'animal/image_upload_form.html', {'form': form})


def classify_image(request, pk):
    # origin image's variables
    origin_image = Image.objects.get(pk=pk)
    origin_path = os.path.join(r'', origin_image.content.path)

    # [START check_is_already_classified]
    try:
        result = ClassificationResult.objects.get(pk=pk)
        return redirect(result)
    except Exception as e:
        pass

    # [END check_is_already_classified]

    # [START classify_image]
    classifier = AnimalClassification(origin_path)
    label, probability = classifier.run_graph()
    # [END classify_image]

    # [START save_result_to_model]
    result = ClassificationResult()
    result.origin = origin_image
    result.label = str(label)
    probability = max(probability[0])
    result.probability = float(probability)

    try:
        result.save()
    except Exception as e:
        print('result saving failed: ' + e)
        return redirect(result)
    else:
        print('result saved!')
    # [END save_result_to_model]

    print(origin_path)

    return redirect(result)


# class ImageDetail(DetailView):

class ClassificationResultView(DetailView):
    model = ClassificationResult
    template_name = 'animal/classification_result.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print(context)
        """hello this is test line"""
        return context

_django/templates/animal/classification_result.html
<h1>검사 결과</h1>
<img src="{{object.origin.content.url}}" width="auto" height="auto"/>
{% if object.label == 'Dog' %}
<p>아마... 개인듯?</p>
{% elif object.label == 'Cat' %}
<p>아마... 고냥인듯?</p>
{% endif %}
<p>{{object.probability}}%로...</p>


<button><a href="{% url 'animal:upload' %}">다른 사진 검사하기</a></button>

_django/templates/animal/image_detail.html
{% extends 'animal/layout.html' %}

{% block content %}
{% if image.content %}
path : {{ image.content.path }}
url : {{ image.content.url}}
<img src="{{image.content.url}}" alt=""/>
{% endif %}

{% endblock %}

_django/templates/animal/image_form.html
{% extends 'animal/layout.html' %}

{% block content %}
<form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>

    <button type="submit">Upload</button>
</form>

{% endblock %}

_django/templates/animal/image_upload_form.html
{% extends 'animal/layout.html' %}

{% block content %}
<form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>

    <button type="submit">Upload</button>
</form>

{% endblock %}

_django/templates/animal/layout.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="ko">

<head>
    <title>{% block page_title %}Pystagram{% endblock %}</title>
    <meta charset="utf-8">
    <script type="text/javascript" src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
</head>

<body>
{% block content %}{% endblock %}
</body>

</html>

animal_classification/templates/upload_photo.html
{% extends 'layout.html' %}

{% block content %}
<form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <p>
        <button type="submit">저장</button>
    </p>
</form>

{% endblock %}